### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by NicolasAndrehh** [astroboyReloaded/astroboyReloaded.github.io#13]
# Hi @astroboyReloaded!
Your project is really good designed, but i think there are some things that can be improved
- I notice that you added a hover effect on the recent works cards, i think it would look so much better if add a transition for the hover effect to appear 
- Also in the form there are no placeholder on the inputs, you could add it to improve the user experience
- I like how you do the mobile version but there something that could be improved in the form, i think would be better if you add more gap between the textarea and the button
- Icons in the footer don't follow the figma template, they are spaced out and on figma they are more to the right

**Comment by astroboyReloaded** [comment]
Solved! Thanks!!!
