### ISSUE TITLE
Deploy to Github Pages

### ISSUE THREAD

**Issue by astroboyReloaded** [astroboyReloaded/astroboyReloaded.github.io#9]
**Here's the link to the online version of this app:**
https://astroboyreloaded.github.io/

**Comment by osamaashraf6** [comment]
Hi @astroboyReloaded , 
# STATUS: APPROVED! 🥇🟢🟢💯 
<img src="https://media3.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :ship it: 
Congratulations! 🎉 

## Highlights💯🎈🪄✔️

- [x]  Good deploying at the GitHub pages
- [x] Beautiful UI. ✔️
- [x] Nice design.✔️



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
